### PR TITLE
wip: Adds in rough stack for vicci deployments

### LINKED ISSUE #14: Integrate with AWS Cognito
This way we can have a user login system.

This also puts the consideration of fleshing out a small api for the todos to use with Cognito tokens.

### PR DESCRIPTION
**Pull request by jhechtf**
These changes are the backbone of getting us to use AWS Cognito. They Cognito user pool will be added to the stack at another time, as I am currently testing how to use it generally, let alone through the Cognito generated by the CDK.

Closes #14

### CODE REVIEW

**Review by VincentLeighton — COMMENTED** [review]
Looks like a bunch of json setup, a few tests, and implementing the json.

**Comment by jhechtf** [comment]
I will attempt to get an image up that shows the rough architecture for you. I'm basically aiming for a CDN to deliver the HTML / CSS / JS from Amazon S3

**Comment by jhechtf** [comment]
@VincentLeighton 

Attached is a rough draft of the architecture that will be used to use the items in a live environment.

Vicci Diagram

This is a very simplified view, as the deployment to the S3 bucket will also tell the CloudFront distribution to invalidate any caches so that the new code will be grabbed by users the next time they view the website, but that's hard to denote in the diagram.

The services that will be used are

1. AWS Cognito - a user API as a service.
2. AWS CloudFront - Content distribution service
3. AWS S3 - data storage
4. AWS IAM (for role execution and stack deployment in GitHub actions)
5. AppConfig - Hosted Application Configuration, can be used to rollout features or updates independent of a regular pipeline push (much more advanced use case). For us will simply be a way to collect information about the cognito domain + a perhaps _eventual_ api url.

**Comment by jhechtf** [comment]
Most recent changes successfully create the necessary Cognito resources, as well as populate an AppConfig profile with the necessary information to connect to it in deployment. 

Now thinking about what our `useCognito` hooks needs to do, if it needs to do anything at all. much of the work is already handled in the hook we use [here](https://github.com/jhechtf/vicci/pull/15/files?file-filters%5B%5D=.css&file-filters%5B%5D=.js&file-filters%5B%5D=.json&file-filters%5B%5D=.ts&file-filters%5B%5D=.tsx&file-filters%5B%5D=.yaml#diff-ce2e4c7af9ffe6f7f0a21e2ff1b93ffc9b6e5db61fe9daff37fada7c5e42091eR32). 

An attempt to pull out functions from the `Auth` object to return them from the hook hasn't worked so far. 

It might be possible that the `useCognito` hook only needs to be called once in the main app, since currently it dispatches events to the redux store. We may be able to re-do this so that it gets passed the dispatch function. This would possible allow us to test the code via unit tests (and some planned integ tests).

**Comment by jhechtf** [comment]
Latest commit adds in cognito support and does some reorganization.

This got scope creeped by _a lot_

**Pull request merged**
